{
 "title": "DevHub Campus — annuaire (RED)",
 "tags": [
  "devhub-campus",
  "tp3",
  "annuaire"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_requests_total, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(http_requests_total{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_requests_total{service=\"$service\", namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "build_info_metric", "query": "annuaire_build_info" }
  ]
 },
 "panels": [
  {
   "title": "Request rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"$service\", namespace=\"$namespace\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Error rate (5xx %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{service=\"$service\", namespace=\"$namespace\", status_class=\"5xx\"}[5m]))\n/\nsum(rate(http_requests_total{service=\"$service\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "erreur 5xx"
    }
   ]
  },
  {
   "title": "Latence p50 / p95 / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{service=\"$service\", namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service=\"$service\", namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service=\"$service\", namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Build info (version active)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"$build_info_metric\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}